INSERT INTO DIM_COUNTRIES (name, alpha2_code, alpha3_code, flag) VALUES 
('Zimbabwe', 'ZW', 'ZWE', 'https://cdn.worlddata.info/pics/flags3d/ZWE.png'),
('Zambia', 'ZM', 'ZMB', 'https://cdn.worlddata.info/pics/flags3d/ZMB.png'),
('Yemen', 'YE', 'YEM', 'https://cdn.worlddata.info/pics/flags3d/YEM.png'),
('Western Sahara', 'EH', 'ESH', 'https://cdn.worlddata.info/pics/flags3d/ESH.png'),
('Wallis and Futuna', 'WF', 'WLF', 'https://cdn.worlddata.info/pics/flags3d/WLF.png'),
('Virgin Islands', 'VI', 'VIR', 'https://cdn.worlddata.info/pics/flags3d/VIR.png'),
('Vietnam', 'VN', 'VNM', 'https://cdn.worlddata.info/pics/flags3d/VNM.png'),
('Venezuela', 'VE', 'VEN', 'https://cdn.worlddata.info/pics/flags3d/VEN.png'),
('Vatican City', 'VA', 'VAT', 'https://cdn.worlddata.info/pics/flags3d/VAT.png'),
('Vanuatu', 'VU', 'VUT', 'https://cdn.worlddata.info/pics/flags3d/VUT.png'),
('Uzbekistan', 'UZ', 'UZB', 'https://cdn.worlddata.info/pics/flags3d/UZB.png'),
('Uruguay', 'UY', 'URY', 'https://cdn.worlddata.info/pics/flags3d/URY.png'),
('United States of America', 'US', 'USA', 'https://cdn.worlddata.info/pics/flags3d/USA.png'),
('United States Minor Outlying Islands', 'UM', 'UMI', 'https://cdn.worlddata.info/pics/flags3d/UMI.png'),
('United Kingdom', 'GB', 'GBR', 'https://cdn.worlddata.info/pics/flags3d/GBR.png'),
('United Arab Emirates', 'AE', 'ARE', 'https://cdn.worlddata.info/pics/flags3d/ARE.png'),
('Ukraine', 'UA', 'UKR', 'https://cdn.worlddata.info/pics/flags3d/UKR.png'),
('Uganda', 'UG', 'UGA', 'https://cdn.worlddata.info/pics/flags3d/UGA.png'),
('Tuvalu', 'TV', 'TUV', 'https://cdn.worlddata.info/pics/flags3d/TUV.png'),
('Turks and Caicos Islands', 'TC', 'TCA', 'https://cdn.worlddata.info/pics/flags3d/TCA.png'),
('Turkmenistan', 'TM', 'TKM', 'https://cdn.worlddata.info/pics/flags3d/TKM.png'),
('Turkey', 'TR', 'TUR', 'https://cdn.worlddata.info/pics/flags3d/TUR.png'),
('Tunisia', 'TN', 'TUN', 'https://cdn.worlddata.info/pics/flags3d/TUN.png'),
('Trinidad and Tobago', 'TT', 'TTO', 'https://cdn.worlddata.info/pics/flags3d/TTO.png'),
('Tonga', 'TO', 'TON', 'https://cdn.worlddata.info/pics/flags3d/TON.png'),
('Tokelau', 'TK', 'TKL', 'https://cdn.worlddata.info/pics/flags3d/TKL.png'),
('Togo', 'TG', 'TGO', 'https://cdn.worlddata.info/pics/flags3d/TGO.png'),
('Thailand', 'TH', 'THA', 'https://cdn.worlddata.info/pics/flags3d/THA.png'),
('Tanzania', 'TZ', 'TZA', 'https://cdn.worlddata.info/pics/flags3d/TZA.png'),
('Tajikistan', 'TJ', 'TJK', 'https://cdn.worlddata.info/pics/flags3d/TJK.png'),
('Taiwan', 'TW', 'TWN', 'https://cdn.worlddata.info/pics/flags3d/TWN.png'),
('Syria', 'SY', 'SYR', 'https://cdn.worlddata.info/pics/flags3d/SYR.png'),
('Switzerland', 'CH', 'CHE', 'https://cdn.worlddata.info/pics/flags3d/CHE.png'),
('Sweden', 'SE', 'SWE', 'https://cdn.worlddata.info/pics/flags3d/SWE.png'),
('Svalbard', 'SJ', 'SJM', 'https://cdn.worlddata.info/pics/flags3d/SJM.png'),
('Suriname', 'SR', 'SUR', 'https://cdn.worlddata.info/pics/flags3d/SUR.png'),
('Sudan', 'SD', 'SDN', 'https://cdn.worlddata.info/pics/flags3d/SDN.png'),
('Sri Lanka', 'LK', 'LKA', 'https://cdn.worlddata.info/pics/flags3d/LKA.png'),
('Spain', 'ES', 'ESP', 'https://cdn.worlddata.info/pics/flags3d/ESP.png'),
('South Sudan', 'SS', 'SSD', 'https://cdn.worlddata.info/pics/flags3d/SSD.png'),
('South Korea', 'KR', 'KOR', 'https://cdn.worlddata.info/pics/flags3d/KOR.png'),
('South Georgia and South Sandwich Islands', 'GS', 'SGS', 'https://cdn.worlddata.info/pics/flags3d/SGS.png'),
('South Africa', 'ZA', 'ZAF', 'https://cdn.worlddata.info/pics/flags3d/ZAF.png'),
('Somalia', 'SO', 'SOM', 'https://cdn.worlddata.info/pics/flags3d/SOM.png'),
('Solomon Islands', 'SB', 'SLB', 'https://cdn.worlddata.info/pics/flags3d/SLB.png'),
('Slovenia', 'SI', 'SVN', 'https://cdn.worlddata.info/pics/flags3d/SVN.png'),
('Slovakia', 'SK', 'SVK', 'https://cdn.worlddata.info/pics/flags3d/SVK.png'),
('Sint Maarten', 'SX', 'SXM', 'https://cdn.worlddata.info/pics/flags3d/SXM.png'),
('Singapore', 'SG', 'SGP', 'https://cdn.worlddata.info/pics/flags3d/SGP.png'),
('Sierra Leone', 'SL', 'SLE', 'https://cdn.worlddata.info/pics/flags3d/SLE.png'),
('Seychelles', 'SC', 'SYC', 'https://cdn.worlddata.info/pics/flags3d/SYC.png'),
('Serbia', 'RS', 'SRB', 'https://cdn.worlddata.info/pics/flags3d/SRB.png'),
('Senegal', 'SN', 'SEN', 'https://cdn.worlddata.info/pics/flags3d/SEN.png'),
('Saudi Arabia', 'SA', 'SAU', 'https://cdn.worlddata.info/pics/flags3d/SAU.png'),
('Sao Tome and Principe', 'ST', 'STP', 'https://cdn.worlddata.info/pics/flags3d/STP.png'),
('San Marino', 'SM', 'SMR', 'https://cdn.worlddata.info/pics/flags3d/SMR.png'),
('Samoa', 'WS', 'WSM', 'https://cdn.worlddata.info/pics/flags3d/WSM.png'),
('Saint Vincent and the Grenadines', 'VC', 'VCT', 'https://cdn.worlddata.info/pics/flags3d/VCT.png'),
('Saint Pierre and Miquelon', 'PM', 'SPM', 'https://cdn.worlddata.info/pics/flags3d/SPM.png'),
('Saint Martin', 'MF', 'MAF', 'https://cdn.worlddata.info/pics/flags3d/MAF.png'),
('Saint Lucia', 'LC', 'LCA', 'https://cdn.worlddata.info/pics/flags3d/LCA.png'),
('Saint Kitts and Nevis', 'KN', 'KNA', 'https://cdn.worlddata.info/pics/flags3d/KNA.png'),
('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', 'https://cdn.worlddata.info/pics/flags3d/SHN.png'),
('Saint Barthelemy', 'BL', 'BLM', 'https://cdn.worlddata.info/pics/flags3d/BLM.png'),
('Rwanda', 'RW', 'RWA', 'https://cdn.worlddata.info/pics/flags3d/RWA.png'),
('Russia', 'RU', 'RUS', 'https://cdn.worlddata.info/pics/flags3d/RUS.png'),
('Romania', 'RO', 'ROU', 'https://cdn.worlddata.info/pics/flags3d/ROU.png'),
('Reunion', 'RE', 'REU', 'https://cdn.worlddata.info/pics/flags3d/REU.png'),
('Republic of the Congo', 'CG', 'COG', 'https://cdn.worlddata.info/pics/flags3d/COG.png'),
('Qatar', 'QA', 'QAT', 'https://cdn.worlddata.info/pics/flags3d/QAT.png'),
('Puerto Rico', 'PR', 'PRI', 'https://cdn.worlddata.info/pics/flags3d/PRI.png'),
('Principality of Monaco', 'MC', 'MCO', 'https://cdn.worlddata.info/pics/flags3d/MCO.png'),
('Portugal', 'PT', 'PRT', 'https://cdn.worlddata.info/pics/flags3d/PRT.png'),
('Poland', 'PL', 'POL', 'https://cdn.worlddata.info/pics/flags3d/POL.png'),
('Pitcairn Islands', 'PN', 'PCN', 'https://cdn.worlddata.info/pics/flags3d/PCN.png'),
('Philippines', 'PH', 'PHL', 'https://cdn.worlddata.info/pics/flags3d/PHL.png'),
('Peru', 'PE', 'PER', 'https://cdn.worlddata.info/pics/flags3d/PER.png'),
('Paraguay', 'PY', 'PRY', 'https://cdn.worlddata.info/pics/flags3d/PRY.png'),
('Papua New Guinea', 'PG', 'PNG', 'https://cdn.worlddata.info/pics/flags3d/PNG.png'),
('Panama', 'PA', 'PAN', 'https://cdn.worlddata.info/pics/flags3d/PAN.png'),
('Palestine', 'PS', 'PSE', 'https://cdn.worlddata.info/pics/flags3d/PSE.png'),
('Palau', 'PW', 'PLW', 'https://cdn.worlddata.info/pics/flags3d/PLW.png'),
('Pakistan', 'PK', 'PAK', 'https://cdn.worlddata.info/pics/flags3d/PAK.png'),
('Oman', 'OM', 'OMN', 'https://cdn.worlddata.info/pics/flags3d/OMN.png'),
('Norway', 'NO', 'NOR', 'https://cdn.worlddata.info/pics/flags3d/NOR.png'),
('Northern Mariana Islands', 'MP', 'MNP', 'https://cdn.worlddata.info/pics/flags3d/MNP.png'),
('North Macedonia', 'MK', 'MKD', 'https://cdn.worlddata.info/pics/flags3d/MKD.png'),
('North Korea', 'KP', 'PRK', 'https://cdn.worlddata.info/pics/flags3d/PRK.png'),
('Norfolk Island', 'NF', 'NFK', 'https://cdn.worlddata.info/pics/flags3d/NFK.png'),
('Niue', 'NU', 'NIU', 'https://cdn.worlddata.info/pics/flags3d/NIU.png'),
('Nigeria', 'NG', 'NGA', 'https://cdn.worlddata.info/pics/flags3d/NGA.png'),
('Niger', 'NE', 'NER', 'https://cdn.worlddata.info/pics/flags3d/NER.png'),
('Nicaragua', 'NI', 'NIC', 'https://cdn.worlddata.info/pics/flags3d/NIC.png'),
('New Zealand', 'NZ', 'NZL', 'https://cdn.worlddata.info/pics/flags3d/NZL.png'),
('New Caledonia', 'NC', 'NCL', 'https://cdn.worlddata.info/pics/flags3d/NCL.png'),
('Netherlands', 'NL', 'NLD', 'https://cdn.worlddata.info/pics/flags3d/NLD.png'),
('Nepal', 'NP', 'NPL', 'https://cdn.worlddata.info/pics/flags3d/NPL.png'),
('Nauru', 'NR', 'NRU', 'https://cdn.worlddata.info/pics/flags3d/NRU.png'),
('Namibia', 'NA', 'NAM', 'https://cdn.worlddata.info/pics/flags3d/NAM.png'),
('Myanmar', 'MM', 'MMR', 'https://cdn.worlddata.info/pics/flags3d/MMR.png'),
('Mozambique', 'MZ', 'MOZ', 'https://cdn.worlddata.info/pics/flags3d/MOZ.png'),
('Morocco', 'MA', 'MAR', 'https://cdn.worlddata.info/pics/flags3d/MAR.png'),
('Montserrat', 'MS', 'MSR', 'https://cdn.worlddata.info/pics/flags3d/MSR.png'),
('Montenegro', 'ME', 'MNE', 'https://cdn.worlddata.info/pics/flags3d/MNE.png'),
('Mongolia', 'MN', 'MNG', 'https://cdn.worlddata.info/pics/flags3d/MNG.png'),
('Moldova', 'MD', 'MDA', 'https://cdn.worlddata.info/pics/flags3d/MDA.png'),
('Mexico', 'MX', 'MEX', 'https://cdn.worlddata.info/pics/flags3d/MEX.png'),
('Mayotte', 'YT', 'MYT', 'https://cdn.worlddata.info/pics/flags3d/MYT.png'),
('Mauritius', 'MU', 'MUS', 'https://cdn.worlddata.info/pics/flags3d/MUS.png'),
('Mauritania', 'MR', 'MRT', 'https://cdn.worlddata.info/pics/flags3d/MRT.png'),
('Martinique', 'MQ', 'MTQ', 'https://cdn.worlddata.info/pics/flags3d/MTQ.png'),
('Marshall Islands', 'MH', 'MHL', 'https://cdn.worlddata.info/pics/flags3d/MHL.png'),
('Malta', 'MT', 'MLT', 'https://cdn.worlddata.info/pics/flags3d/MLT.png'),
('Mali', 'ML', 'MLI', 'https://cdn.worlddata.info/pics/flags3d/MLI.png'),
('Maldives', 'MV', 'MDV', 'https://cdn.worlddata.info/pics/flags3d/MDV.png'),
('Malaysia', 'MY', 'MYS', 'https://cdn.worlddata.info/pics/flags3d/MYS.png'),
('Malawi', 'MW', 'MWI', 'https://cdn.worlddata.info/pics/flags3d/MWI.png'),
('Madagascar', 'MG', 'MDG', 'https://cdn.worlddata.info/pics/flags3d/MDG.png'),
('Macao', 'MO', 'MAC', 'https://cdn.worlddata.info/pics/flags3d/MAC.png'),
('Luxembourg', 'LU', 'LUX', 'https://cdn.worlddata.info/pics/flags3d/LUX.png'),
('Lithuania', 'LT', 'LTU', 'https://cdn.worlddata.info/pics/flags3d/LTU.png'),
('Liechtenstein', 'LI', 'LIE', 'https://cdn.worlddata.info/pics/flags3d/LIE.png'),
('Libya', 'LY', 'LBY', 'https://cdn.worlddata.info/pics/flags3d/LBY.png'),
('Liberia', 'LR', 'LBR', 'https://cdn.worlddata.info/pics/flags3d/LBR.png'),
('Lesotho', 'LS', 'LSO', 'https://cdn.worlddata.info/pics/flags3d/LSO.png'),
('Lebanon', 'LB', 'LBN', 'https://cdn.worlddata.info/pics/flags3d/LBN.png'),
('Latvia', 'LV', 'LVA', 'https://cdn.worlddata.info/pics/flags3d/LVA.png'),
('Laos', 'LA', 'LAO', 'https://cdn.worlddata.info/pics/flags3d/LAO.png'),
('Kyrgyzstan', 'KG', 'KGZ', 'https://cdn.worlddata.info/pics/flags3d/KGZ.png'),
('Kuwait', 'KW', 'KWT', 'https://cdn.worlddata.info/pics/flags3d/KWT.png'),
('Kosovo', 'XK', 'XXK', 'https://cdn.worlddata.info/pics/flags3d/XXK.png'),
('Kiribati', 'KI', 'KIR', 'https://cdn.worlddata.info/pics/flags3d/KIR.png'),
('Kenya', 'KE', 'KEN', 'https://cdn.worlddata.info/pics/flags3d/KEN.png'),
('Kazakhstan', 'KZ', 'KAZ', 'https://cdn.worlddata.info/pics/flags3d/KAZ.png'),
('Jordan', 'JO', 'JOR', 'https://cdn.worlddata.info/pics/flags3d/JOR.png'),
('Jersey', 'JE', 'JEY', 'https://cdn.worlddata.info/pics/flags3d/JEY.png'),
('Japan', 'JP', 'JPN', 'https://cdn.worlddata.info/pics/flags3d/JPN.png'),
('Jamaica', 'JM', 'JAM', 'https://cdn.worlddata.info/pics/flags3d/JAM.png'),
('Ivory Coast', 'CI', 'CIV', 'https://cdn.worlddata.info/pics/flags3d/CIV.png'),
('Italy', 'IT', 'ITA', 'https://cdn.worlddata.info/pics/flags3d/ITA.png'),
('Israel', 'IL', 'ISR', 'https://cdn.worlddata.info/pics/flags3d/ISR.png'),
('Isle of Man', 'IM', 'IMN', 'https://cdn.worlddata.info/pics/flags3d/IMN.png'),
('Ireland', 'IE', 'IRL', 'https://cdn.worlddata.info/pics/flags3d/IRL.png'),
('Iraq', 'IQ', 'IRQ', 'https://cdn.worlddata.info/pics/flags3d/IRQ.png'),
('Iran', 'IR', 'IRN', 'https://cdn.worlddata.info/pics/flags3d/IRN.png'),
('Indonesia', 'ID', 'IDN', 'https://cdn.worlddata.info/pics/flags3d/IDN.png'),
('India', 'IN', 'IND', 'https://cdn.worlddata.info/pics/flags3d/IND.png'),
('Iceland', 'IS', 'ISL', 'https://cdn.worlddata.info/pics/flags3d/ISL.png'),
('Hungary', 'HU', 'HUN', 'https://cdn.worlddata.info/pics/flags3d/HUN.png'),
('Hong Kong', 'HK', 'HKG', 'https://cdn.worlddata.info/pics/flags3d/HKG.png'),
('Honduras', 'HN', 'HND', 'https://cdn.worlddata.info/pics/flags3d/HND.png'),
('Heard Island and McDonald Islands', 'HM', 'HMD', 'https://cdn.worlddata.info/pics/flags3d/HMD.png'),
('Haiti', 'HT', 'HTI', 'https://cdn.worlddata.info/pics/flags3d/HTI.png'),
('Guyana', 'GY', 'GUY', 'https://cdn.worlddata.info/pics/flags3d/GUY.png'),
('Guinea', 'GN', 'GIN', 'https://cdn.worlddata.info/pics/flags3d/GIN.png'),
('Guinea-Bissau', 'GW', 'GNB', 'https://cdn.worlddata.info/pics/flags3d/GNB.png'),
('Guernsey', 'GG', 'GGY', 'https://cdn.worlddata.info/pics/flags3d/GGY.png'),
('Guatemala', 'GT', 'GTM', 'https://cdn.worlddata.info/pics/flags3d/GTM.png'),
('Guam', 'GU', 'GUM', 'https://cdn.worlddata.info/pics/flags3d/GUM.png'),
('Guadeloupe', 'GP', 'GLP', 'https://cdn.worlddata.info/pics/flags3d/GLP.png'),
('Grenada', 'GD', 'GRD', 'https://cdn.worlddata.info/pics/flags3d/GRD.png'),
('Greenland', 'GL', 'GRL', 'https://cdn.worlddata.info/pics/flags3d/GRL.png'),
('Greece', 'GR', 'GRC', 'https://cdn.worlddata.info/pics/flags3d/GRC.png'),
('Gibraltar', 'GI', 'GIB', 'https://cdn.worlddata.info/pics/flags3d/GIB.png'),
('Ghana', 'GH', 'GHA', 'https://cdn.worlddata.info/pics/flags3d/GHA.png'),
('Germany', 'DE', 'DEU', 'https://cdn.worlddata.info/pics/flags3d/DEU.png'),
('Georgia', 'GE', 'GEO', 'https://cdn.worlddata.info/pics/flags3d/GEO.png'),
('Gambia', 'GM', 'GMB', 'https://cdn.worlddata.info/pics/flags3d/GMB.png'),
('Gabon', 'GA', 'GAB', 'https://cdn.worlddata.info/pics/flags3d/GAB.png'),
('French Southern and Antarctic Lands', 'TF', 'ATF', 'https://cdn.worlddata.info/pics/flags3d/ATF.png'),
('French Polynesia', 'PF', 'PYF', 'https://cdn.worlddata.info/pics/flags3d/PYF.png'),
('French Guiana', 'GF', 'GUF', 'https://cdn.worlddata.info/pics/flags3d/GUF.png'),
('France', 'FR', 'FRA', 'https://cdn.worlddata.info/pics/flags3d/FRA.png'),
('Finland', 'FI', 'FIN', 'https://cdn.worlddata.info/pics/flags3d/FIN.png'),
('Fiji', 'FJ', 'FJI', 'https://cdn.worlddata.info/pics/flags3d/FJI.png'),
('Federated States of Micronesia', 'FM', 'FSM', 'https://cdn.worlddata.info/pics/flags3d/FSM.png'),
('Faroe Islands', 'FO', 'FRO', 'https://cdn.worlddata.info/pics/flags3d/FRO.png'),
('Falkland Islands', 'FK', 'FLK', 'https://cdn.worlddata.info/pics/flags3d/FLK.png'),
('Ethiopia', 'ET', 'ETH', 'https://cdn.worlddata.info/pics/flags3d/ETH.png'),
('Eswatini', 'SZ', 'SWZ', 'https://cdn.worlddata.info/pics/flags3d/SWZ.png'),
('Estonia', 'EE', 'EST', 'https://cdn.worlddata.info/pics/flags3d/EST.png'),
('Eritrea', 'ER', 'ERI', 'https://cdn.worlddata.info/pics/flags3d/ERI.png'),
('Equatorial Guinea', 'GQ', 'GNQ', 'https://cdn.worlddata.info/pics/flags3d/GNQ.png'),
('El Salvador', 'SV', 'SLV', 'https://cdn.worlddata.info/pics/flags3d/SLV.png'),
('Egypt', 'EG', 'EGY', 'https://cdn.worlddata.info/pics/flags3d/EGY.png'),
('Ecuador', 'EC', 'ECU', 'https://cdn.worlddata.info/pics/flags3d/ECU.png'),
('East Timor', 'TL', 'TLS', 'https://cdn.worlddata.info/pics/flags3d/TLS.png'),
('Dominican Republic', 'DO', 'DOM', 'https://cdn.worlddata.info/pics/flags3d/DOM.png'),
('Dominica', 'DM', 'DMA', 'https://cdn.worlddata.info/pics/flags3d/DMA.png'),
('Djibouti', 'DJ', 'DJI', 'https://cdn.worlddata.info/pics/flags3d/DJI.png'),
('Denmark', 'DK', 'DNK', 'https://cdn.worlddata.info/pics/flags3d/DNK.png'),
('Democratic Republic of the Congo', 'CD', 'COD', 'https://cdn.worlddata.info/pics/flags3d/COD.png'),
('Czechia', 'CZ', 'CZE', 'https://cdn.worlddata.info/pics/flags3d/CZE.png'),
('Cyprus', 'CY', 'CYP', 'https://cdn.worlddata.info/pics/flags3d/CYP.png'),
('Curacao', 'CW', 'CUW', 'https://cdn.worlddata.info/pics/flags3d/CUW.png'),
('Cuba', 'CU', 'CUB', 'https://cdn.worlddata.info/pics/flags3d/CUB.png'),
('Croatia', 'HR', 'HRV', 'https://cdn.worlddata.info/pics/flags3d/HRV.png'),
('Costa Rica', 'CR', 'CRI', 'https://cdn.worlddata.info/pics/flags3d/CRI.png'),
('Cook Islands', 'CK', 'COK', 'https://cdn.worlddata.info/pics/flags3d/COK.png'),
('Comoros', 'KM', 'COM', 'https://cdn.worlddata.info/pics/flags3d/COM.png'),
('Colombia', 'CO', 'COL', 'https://cdn.worlddata.info/pics/flags3d/COL.png'),
('Cocos (Keeling) Islands', 'CC', 'CCK', 'https://cdn.worlddata.info/pics/flags3d/CCK.png'),
('Christmas Island', 'CX', 'CXR', 'https://cdn.worlddata.info/pics/flags3d/CXR.png'),
('China', 'CN', 'CHN', 'https://cdn.worlddata.info/pics/flags3d/CHN.png'),
('Chile', 'CL', 'CHL', 'https://cdn.worlddata.info/pics/flags3d/CHL.png'),
('Chad', 'TD', 'TCD', 'https://cdn.worlddata.info/pics/flags3d/TCD.png'),
('Central African Republic', 'CF', 'CAF', 'https://cdn.worlddata.info/pics/flags3d/CAF.png'),
('Cayman Islands', 'KY', 'CYM', 'https://cdn.worlddata.info/pics/flags3d/CYM.png'),
('Caribbean Netherlands', 'BQ', 'BES', 'https://cdn.worlddata.info/pics/flags3d/BES.png'),
('Cape Verde', 'CV', 'CPV', 'https://cdn.worlddata.info/pics/flags3d/CPV.png'),
('Canada', 'CA', 'CAN', 'https://cdn.worlddata.info/pics/flags3d/CAN.png'),
('Cameroon', 'CM', 'CMR', 'https://cdn.worlddata.info/pics/flags3d/CMR.png'),
('Cambodia', 'KH', 'KHM', 'https://cdn.worlddata.info/pics/flags3d/KHM.png'),
('Burundi', 'BI', 'BDI', 'https://cdn.worlddata.info/pics/flags3d/BDI.png'),
('Burkina Faso', 'BF', 'BFA', 'https://cdn.worlddata.info/pics/flags3d/BFA.png'),
('Bulgaria', 'BG', 'BGR', 'https://cdn.worlddata.info/pics/flags3d/BGR.png'),
('Brunei', 'BN', 'BRN', 'https://cdn.worlddata.info/pics/flags3d/BRN.png'),
('British Virgin Islands', 'VG', 'VGB', 'https://cdn.worlddata.info/pics/flags3d/VGB.png'),
('British Indian Ocean Territory', 'IO', 'IOT', 'https://cdn.worlddata.info/pics/flags3d/IOT.png'),
('Brazil', 'BR', 'BRA', 'https://cdn.worlddata.info/pics/flags3d/BRA.png'),
('Bouvet Island', 'BV', 'BVT', 'https://cdn.worlddata.info/pics/flags3d/BVT.png'),
('Botswana', 'BW', 'BWA', 'https://cdn.worlddata.info/pics/flags3d/BWA.png'),
('Bosnia and Herzegovina', 'BA', 'BIH', 'https://cdn.worlddata.info/pics/flags3d/BIH.png'),
('Bolivia', 'BO', 'BOL', 'https://cdn.worlddata.info/pics/flags3d/BOL.png'),
('Bhutan', 'BT', 'BTN', 'https://cdn.worlddata.info/pics/flags3d/BTN.png'),
('Bermuda', 'BM', 'BMU', 'https://cdn.worlddata.info/pics/flags3d/BMU.png'),
('Benin', 'BJ', 'BEN', 'https://cdn.worlddata.info/pics/flags3d/BEN.png'),
('Belize', 'BZ', 'BLZ', 'https://cdn.worlddata.info/pics/flags3d/BLZ.png'),
('Belgium', 'BE', 'BEL', 'https://cdn.worlddata.info/pics/flags3d/BEL.png'),
('Belarus', 'BY', 'BLR', 'https://cdn.worlddata.info/pics/flags3d/BLR.png'),
('Barbados', 'BB', 'BRB', 'https://cdn.worlddata.info/pics/flags3d/BRB.png'),
('Bangladesh', 'BD', 'BGD', 'https://cdn.worlddata.info/pics/flags3d/BGD.png'),
('Bahrain', 'BH', 'BHR', 'https://cdn.worlddata.info/pics/flags3d/BHR.png'),
('Bahamas', 'BS', 'BHS', 'https://cdn.worlddata.info/pics/flags3d/BHS.png'),
('Azerbaijan', 'AZ', 'AZE', 'https://cdn.worlddata.info/pics/flags3d/AZE.png'),
('Austria', 'AT', 'AUT', 'https://cdn.worlddata.info/pics/flags3d/AUT.png'),
('Australia', 'AU', 'AUS', 'https://cdn.worlddata.info/pics/flags3d/AUS.png'),
('Aruba', 'AW', 'ABW', 'https://cdn.worlddata.info/pics/flags3d/ABW.png'),
('Armenia', 'AM', 'ARM', 'https://cdn.worlddata.info/pics/flags3d/ARM.png'),
('Argentina', 'AR', 'ARG', 'https://cdn.worlddata.info/pics/flags3d/ARG.png'),
('Antigua and Barbuda', 'AG', 'ATG', 'https://cdn.worlddata.info/pics/flags3d/ATG.png'),
('Antarctica', 'AQ', 'ATA', 'https://cdn.worlddata.info/pics/flags3d/ATA.png'),
('Anguilla', 'AI', 'AIA', 'https://cdn.worlddata.info/pics/flags3d/AIA.png'),
('Angola', 'AO', 'AGO', 'https://cdn.worlddata.info/pics/flags3d/AGO.png'),
('Andorra', 'AD', 'AND', 'https://cdn.worlddata.info/pics/flags3d/AND.png'),
('American Samoa', 'AS', 'ASM', 'https://cdn.worlddata.info/pics/flags3d/ASM.png'),
('Algeria', 'DZ', 'DZA', 'https://cdn.worlddata.info/pics/flags3d/DZA.png'),
('Albania', 'AL', 'ALB', 'https://cdn.worlddata.info/pics/flags3d/ALB.png'),
('Åland Islands', 'AX', 'ALA', 'https://cdn.worlddata.info/pics/flags3d/ALA.png'),
('Afghanistan', 'AF', 'AFG', 'https://cdn.worlddata.info/pics/flags3d/AFG.png');